import { ProjectFullState } from '../types';

export function createDemoProject(): ProjectFullState {
  const projectId = 'demo-sprintflow-aura';
  const now = new Date().toISOString();

  const project = {
    id: projectId,
    name: 'AuraFlow — Visual Feedback Suite (Demo Project)',
    description: 'Collaborative real-time canvas for design reviews, browser-based video annotation, and sprint-ready issue export.',
    scenario: 'Building a cloud-first design review tool that allows cross-functional teams to drop comments directly on live URLs and Figma frames, auto-generate tickets, and sync with sprint backlogs.',
    start_date: '2026-09-15',
    deadline: null, // intentionally missing to demonstrate [ Add deadline ]
    sprint_duration: 2,
    project_type: 'Web Application & Browser Extension',
    tech_stack: ['React', 'TypeScript', 'TailwindCSS', 'WebRTC', 'Supabase', 'Node.js'],
    goals: [
      'Enable sub-100ms video screen recording and annotation in Chrome',
      'Provide bi-directional sync with sprint tracking tools',
      'Deliver frictionless client presentation mode'
    ],
    requirements: [
      'Canvas annotation overlay over iframed DOM',
      'Role-based access (Reviewer, Contributor, Admin)',
      'High-resolution canvas screenshot exporter'
    ],
    created_at: now,
    updated_at: now,
    is_demo: true,
  };

  const teamMembers = [
    {
      id: 'tm-1',
      project_id: projectId,
      name: 'Sara Chen',
      role: 'Frontend Lead',
      skills: ['React', 'Canvas API', 'TypeScript'],
      email: 'sara@example.com',
      created_at: now,
    },
    {
      id: 'tm-2',
      project_id: projectId,
      name: 'Marcus Vance',
      role: 'Backend Architect',
      skills: ['Node.js', 'PostgreSQL', 'WebSockets', 'Supabase'],
      email: 'marcus@example.com',
      created_at: now,
    },
    {
      id: 'tm-3',
      project_id: projectId,
      name: 'Elena Rostova',
      role: 'UX / Product Designer',
      skills: ['Design Systems', 'Figma', 'User Research'],
      created_at: now,
    }
  ];

  const epics = [
    {
      id: 'epic-1',
      epic_code: 'EP-01',
      project_id: projectId,
      title: 'Interactive Review Canvas & Overlays',
      description: 'Core drawing, pinning, and interactive thread capability directly on top of web surfaces.',
      goal: 'Allow instant pinpoint feedback on any visual element with precision coordinates.',
      priority: 'critical' as const,
      progress: 65,
      created_at: now,
      updated_at: now,
      is_ai_suggested: false,
    },
    {
      id: 'epic-2',
      epic_code: 'EP-02',
      project_id: projectId,
      title: 'Real-time Collaboration & Presence',
      description: 'Multi-cursor presence, live audio huddles, and synchronized viewport states.',
      goal: 'Teams can review prototypes synchronously without third-party screen sharing.',
      priority: 'high' as const,
      progress: 30,
      created_at: now,
      updated_at: now,
      is_ai_suggested: true,
    },
    {
      id: 'epic-3',
      epic_code: 'EP-03',
      project_id: projectId,
      title: 'Sprint Planning & Exporter Engine',
      description: 'Transform visual review cards into actionable sprint tasks and downloadable PDF reports.',
      goal: 'Zero manual transcription from design reviews into developer backlogs.',
      priority: 'medium' as const,
      progress: 10,
      created_at: now,
      updated_at: now,
      is_ai_suggested: true,
    }
  ];

  const sprints = [
    {
      id: 'sprint-1',
      project_id: projectId,
      name: 'Sprint 1: Canvas Core & Pinning',
      sprint_number: 1,
      goal: 'Deliver working multi-layer viewport with draggable comment pins and DOM snapshotting.',
      start_date: '2026-09-15',
      end_date: '2026-09-29',
      capacity: 26,
      status: 'active' as const,
      created_at: now,
      updated_at: now,
      is_ai_suggested: false
    },
    {
      id: 'sprint-2',
      project_id: projectId,
      name: 'Sprint 2: Real-time Presence & Threads',
      sprint_number: 2,
      goal: 'Synchronize collaborative cursors, threaded discussions, and mention notifications.',
      start_date: '2026-09-30',
      end_date: '2026-10-14',
      capacity: 24,
      status: 'planned' as const,
      created_at: now,
      updated_at: now,
      is_ai_suggested: true
    },
    {
      id: 'sprint-3',
      project_id: projectId,
      name: 'Sprint 3: Export & Jira/Linear Webhooks',
      sprint_number: 3,
      goal: 'Generate PDF executive summaries and trigger automated webhook ticket generation.',
      start_date: '2026-10-15',
      end_date: '2026-10-29',
      capacity: 20,
      status: 'planned' as const,
      created_at: now,
      updated_at: now,
      is_ai_suggested: true
    }
  ];

  const backlogItems = [
    {
      id: 'task-101',
      item_code: 'SF-101',
      project_id: projectId,
      epic_id: 'epic-1',
      title: 'Canvas Coordinate Transform & Zoom Matrix',
      description: 'Implement pan-zoom viewport matrix with DPR calibration for crisp retina rendering.',
      priority: 'critical' as const,
      story_points: 8,
      assignee_id: 'tm-1',
      sprint_id: 'sprint-1',
      status: 'done' as const,
      ai_suggested: false,
      created_at: now,
      updated_at: now,
    },
    {
      id: 'task-102',
      item_code: 'SF-102',
      project_id: projectId,
      epic_id: 'epic-1',
      title: 'Pin Marker Placement & Drag Anchors',
      description: 'Allow clicking any canvas node to attach numbered indicator with threaded reply popover.',
      priority: 'high' as const,
      story_points: 5,
      assignee_id: 'tm-1',
      sprint_id: 'sprint-1',
      status: 'in_progress' as const,
      ai_suggested: false,
      created_at: now,
      updated_at: now,
    },
    {
      id: 'task-103',
      item_code: 'SF-103',
      project_id: projectId,
      epic_id: 'epic-1',
      title: 'High-Res Viewport Screenshot Capture',
      description: 'Capture clean PNG snapshot of composite DOM elements ignoring floating UI overlays.',
      priority: 'medium' as const,
      story_points: 5,
      assignee_id: 'tm-2',
      sprint_id: 'sprint-1',
      status: 'todo' as const,
      ai_suggested: true,
      created_at: now,
      updated_at: now,
    },
    {
      id: 'task-104',
      item_code: 'SF-104',
      project_id: projectId,
      epic_id: 'epic-2',
      title: 'WebSocket Cursor Broadcast & Presence Channel',
      description: 'Stream cursor coordinates with 60fps smoothing using binary ArrayBuffers.',
      priority: 'high' as const,
      story_points: 8,
      assignee_id: 'tm-2',
      sprint_id: 'sprint-2',
      status: 'todo' as const,
      ai_suggested: true,
      suggested_assignee_id: 'tm-2',
      ai_suggestion_rationale: 'Marcus is backend architect with WebSocket & Supabase experience.',
      created_at: now,
      updated_at: now,
    },
    {
      id: 'task-105',
      item_code: 'SF-105',
      project_id: projectId,
      epic_id: 'epic-2',
      title: 'Threaded Comment State Machine',
      description: 'Resolve, reopen, and react to comments with optimistic local UI updates.',
      priority: 'medium' as const,
      story_points: 5,
      assignee_id: null, // Unassigned to show [ Select team member ]
      sprint_id: 'sprint-2',
      status: 'todo' as const,
      ai_suggested: true,
      suggested_assignee_id: 'tm-1',
      ai_suggestion_rationale: 'Sara has extensive React state management expertise.',
      created_at: now,
      updated_at: now,
    },
    {
      id: 'task-106',
      item_code: 'SF-106',
      project_id: projectId,
      epic_id: 'epic-2',
      title: 'Real-time Peer Audio Huddle (WebRTC)',
      description: 'Enable mesh WebRTC audio channel for 2-6 collaborators during synchronous reviews.',
      priority: 'high' as const,
      story_points: 13,
      assignee_id: null,
      sprint_id: 'sprint-2', // Makes Sprint 2 planned points = 8+5+13=26 (over 24 capacity => tests "Sprint overloaded" warning!)
      status: 'todo' as const,
      ai_suggested: true,
      created_at: now,
      updated_at: now,
    },
    {
      id: 'task-107',
      item_code: 'SF-107',
      project_id: projectId,
      epic_id: 'epic-3',
      title: 'Client Presentation Deck Exporter (PDF)',
      description: 'Assemble all pinned findings, screenshots, and resolved threads into a client-ready PDF.',
      priority: 'medium' as const,
      story_points: 8,
      assignee_id: null,
      sprint_id: 'sprint-3',
      status: 'todo' as const,
      ai_suggested: true,
      created_at: now,
      updated_at: now,
    },
    {
      id: 'task-108',
      item_code: 'SF-108',
      project_id: projectId,
      epic_id: 'epic-3',
      title: 'Jira & Linear Webhook Two-Way Sync',
      description: 'Create issues from marked pins and receive webhook callbacks on ticket status transitions.',
      priority: 'high' as const,
      story_points: 8,
      assignee_id: null,
      sprint_id: null, // In Backlog
      status: 'todo' as const,
      ai_suggested: true,
      created_at: now,
      updated_at: now,
    },
    {
      id: 'task-109',
      item_code: 'SF-109',
      project_id: projectId,
      epic_id: null,
      title: 'Keyboard Shortcuts Cheat-sheet & Focus Traps',
      description: 'Add accessibility focus trap handling and quick keys: V (select), P (pin), C (comment).',
      priority: 'low' as const,
      story_points: 3,
      assignee_id: null,
      sprint_id: null, // In Backlog
      status: 'todo' as const,
      ai_suggested: true,
      created_at: now,
      updated_at: now,
    }
  ];

  const dependencies = [
    {
      id: 'dep-1',
      project_id: projectId,
      source_item_id: 'task-101',
      target_item_id: 'task-102',
      dependency_type: 'blocks' as const,
      description: 'Zoom matrix required before pin coordinates can be mapped onto canvas space.',
      created_at: now,
    },
    {
      id: 'dep-2',
      project_id: projectId,
      source_item_id: 'task-104',
      target_item_id: 'task-106',
      dependency_type: 'depends_on' as const,
      description: 'WebRTC signaling relies on active WebSocket connection.',
      created_at: now,
    }
  ];

  const risks = [
    {
      id: 'risk-1',
      project_id: projectId,
      title: 'Cross-Origin Iframe DOM Security (CORS)',
      severity: 'critical' as const,
      impact: 'Browsers block script injection into third-party target iframes without browser extension.',
      mitigation: 'Implement proxy renderer fallback and dedicated Chrome Manifest V3 companion extension.',
      created_at: now,
    },
    {
      id: 'risk-2',
      project_id: projectId,
      title: 'Sprint 2 Workload Exceeds Recommended Velocity',
      severity: 'high' as const,
      impact: 'Sprint 2 has 26 points against 24 capacity with high complexity in WebRTC audio.',
      mitigation: 'Move WebRTC audio task (13 pts) to dedicated technical spike or Sprint 3.',
      created_at: now,
    }
  ];

  const milestones = [
    {
      id: 'ms-1',
      project_id: projectId,
      title: 'Alpha Internal Dogfooding',
      due_date: '2026-10-01',
      completed: false,
      created_at: now,
    },
    {
      id: 'ms-2',
      project_id: projectId,
      title: 'Beta Launch with 10 Partner Agencies',
      due_date: '2026-11-01',
      completed: false,
      created_at: now,
    }
  ];

  // Hierarchical canvas block positioning:
  // Layer 0: Project Overview Block
  // Layer 1: Epics row
  // Layer 2: Sprints row
  // Layer 3: Backlog & Risks row
  const canvasBlocks = [
    {
      id: 'cb-project',
      project_id: projectId,
      entity_type: 'project' as const,
      entity_id: projectId,
      block_type: 'project_overview',
      x: 100,
      y: 80,
      width: 480,
      height: 380,
      z_index: 2,
      created_at: now,
      updated_at: now,
    },
    {
      id: 'cb-analytics',
      project_id: projectId,
      entity_type: 'progress' as const,
      entity_id: projectId,
      block_type: 'analytics',
      x: 620,
      y: 80,
      width: 420,
      height: 380,
      z_index: 2,
      created_at: now,
      updated_at: now,
    },
    {
      id: 'cb-team',
      project_id: projectId,
      entity_type: 'team_member' as const,
      entity_id: projectId,
      block_type: 'team_roster',
      x: 1080,
      y: 80,
      width: 400,
      height: 380,
      z_index: 2,
      created_at: now,
      updated_at: now,
    },
    // Epics row (y = 520)
    {
      id: 'cb-epic-1',
      project_id: projectId,
      entity_type: 'epic' as const,
      entity_id: 'epic-1',
      block_type: 'epic',
      x: 100,
      y: 520,
      width: 440,
      height: 290,
      z_index: 3,
      created_at: now,
      updated_at: now,
    },
    {
      id: 'cb-epic-2',
      project_id: projectId,
      entity_type: 'epic' as const,
      entity_id: 'epic-2',
      block_type: 'epic',
      x: 580,
      y: 520,
      width: 440,
      height: 290,
      z_index: 3,
      created_at: now,
      updated_at: now,
    },
    {
      id: 'cb-epic-3',
      project_id: projectId,
      entity_type: 'epic' as const,
      entity_id: 'epic-3',
      block_type: 'epic',
      x: 1060,
      y: 520,
      width: 440,
      height: 290,
      z_index: 3,
      created_at: now,
      updated_at: now,
    },
    // Sprints row (y = 870)
    {
      id: 'cb-sprint-1',
      project_id: projectId,
      entity_type: 'sprint' as const,
      entity_id: 'sprint-1',
      block_type: 'sprint',
      x: 100,
      y: 870,
      width: 440,
      height: 480,
      z_index: 3,
      created_at: now,
      updated_at: now,
    },
    {
      id: 'cb-sprint-2',
      project_id: projectId,
      entity_type: 'sprint' as const,
      entity_id: 'sprint-2',
      block_type: 'sprint',
      x: 580,
      y: 870,
      width: 440,
      height: 480,
      z_index: 3,
      created_at: now,
      updated_at: now,
    },
    {
      id: 'cb-sprint-3',
      project_id: projectId,
      entity_type: 'sprint' as const,
      entity_id: 'sprint-3',
      block_type: 'sprint',
      x: 1060,
      y: 870,
      width: 440,
      height: 480,
      z_index: 3,
      created_at: now,
      updated_at: now,
    },
    // Backlog & Risks row (y = 1410)
    {
      id: 'cb-backlog',
      project_id: projectId,
      entity_type: 'backlog_item' as const,
      entity_id: projectId,
      block_type: 'product_backlog',
      x: 100,
      y: 1410,
      width: 920,
      height: 440,
      z_index: 3,
      created_at: now,
      updated_at: now,
    },
    {
      id: 'cb-risks',
      project_id: projectId,
      entity_type: 'risk' as const,
      entity_id: projectId,
      block_type: 'risk_matrix',
      x: 1060,
      y: 1410,
      width: 440,
      height: 440,
      z_index: 3,
      created_at: now,
      updated_at: now,
    }
  ];

  return {
    project,
    teamMembers,
    epics,
    sprints,
    backlogItems,
    dependencies,
    risks,
    milestones,
    canvasBlocks
  };
}

export { createDemoProject as generateDemoProject };
